# Basic LiveKit configuration for local development
# For more options, see: https://docs.livekit.io/self-hosting/configuration

port: 7880 # API port for clients (WS)
bind_addresses: # Addresses to bind to for the API server
  - 0.0.0.0
rtc:
  tcp_port: 7881

# Development mode settings (optional, useful for local dev)
development: true

# API keys (replace with your own in production)
keys:
  devkey: secret

# Logging configuration
logging:
  level: debug